Auswertungszeitpunkt: 600
Branching:
  chosen: true
  feasibility_stop: false
  feasibility_timelimit: 1
  in_path: ../../../../processed/
  max_iterations: 10
  out_path: ../processed/
  path:
  - ../processed/
  - /Branching/
  results_file: results_branching_improvement_random_29_04.csv
  timeout: 3600
Lagrange:
  c_k: 2
  chosen: false
  feasibility_stop: false
  feasibility_timelimit: 1
  in_path: ../../../processed/
  max_iterations: 10
  out_path: ../processed/
  overall_timeout: 600
  path:
  - ../../processed/
  - /Lagrange/
  results_file: results_lagrange_2903.csv
  timeout: 60
  type_activation: true
  type_sheaf: false
PESP:
  T: 200
  epsilon: 17
  zugfolge: 25
RENS:
  chosen: false
  feasibility_stop: false
  feasibility_timelimit: 1
  fixed_integer_ratio: 0.4
  in_path: ../../processed/
  out_path: ../processed/
  path:
  - ../../processed/
  - /RENS/
  ratios_relax:
  - 0.9
  - 0.6
  relaxed: true
  results_file: results_file_RENS_ineq_0504.csv
  results_file_relaxed: results_file_RENS_relaxed_ineq2803
  timeout: 3600
RINS:
  chosen: false
  epsilon: 0.01
  feasibility_stop: false
  feasibility_timelimit: 1
  in_path: ../../../../processed/
  out_path: ../../processed/
  path:
  - ../../processed/
  - /RINS/
  ratios_relax:
  - 0.9
  - 0.6
  relaxed: true
  results_file: results_file_RINS_ineq.csv
  results_file_relaxed: results_file_RINS_relaxed_random_0504.csv
  timeout: 1800
instances:
- BPKW_BKRW_BSNF_O
- BBOS_BWIN_BTG
main:
  chosen: false
  feasibility_stop: false
  feasibility_timelimit: 1200
  path: ../../processed//original/
  results_file: results_file_main_equality_2703.csv
  timeout: 10800
paths:
  in_path: ../../../processed/
  out_path: ../processed/
